input {
  beats {
    id => "filebeat_input"
    port => 5044
  }

  tcp {
    id => "tcp_json_input"
    port => 5000
    codec => json
    tags => ["tcp_json"]
  }
}

filter {
  if "tcp_json" in [tags] {
    mutate {
      add_field => {
        "event_source" => "tcp_json"
      }
    }
  } else {
    mutate {
      add_field => {
        "event_source" => "docker_filebeat"
      }
    }
  }
}

output {
  if "tcp_json" in [tags] {
    elasticsearch {
      hosts => ["http://es-hot:9200"]
      index => "tcp-json-%{+YYYY.MM.dd}"
      ilm_enabled => false
    }
  } else {
    elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    ilm_enabled => false
    }
  }
    

}
